In [1]:
import numpy as np

# Creating an array


In [2]:
a = np.array([1,2,3])
type(a)

numpy.ndarray

In [3]:
a = np.array([1,2,3], dtype=float)
print(a)

[1. 2. 3.]


In [4]:
a = np.array([1,2,3], dtype=str)
print(a)

['1' '2' '3']


In [5]:
len(a)

3

In [6]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
len(b)

2

In [8]:
c = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
len(c)

3

# Check Diamention

In [10]:
a.ndim

1

In [11]:
c.ndim

2

# Shape of array

In [12]:
a.shape

(3,)

In [13]:
c.shape

(3, 3)

In [14]:
b.dtype

dtype('int64')

# Accessing/changing specific elements, row & column etc.

In [15]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [16]:
a.shape

(2, 7)

In [17]:
# Get item element [r,c]
a[0,3]

np.int64(4)

In [18]:
a[1,4]

np.int64(12)

In [19]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
a[:,2]

array([ 3, 10])

In [21]:
a[0,3] = 99
a

array([[ 1,  2,  3, 99,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

# Zero/One method

In [22]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [23]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.full((3,3), 50, dtype=int)

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [25]:
np.random.rand(3,4)

array([[0.47427647, 0.25591746, 0.50840266, 0.29618279],
       [0.94120685, 0.87182889, 0.184325  , 0.1232302 ],
       [0.50168153, 0.24982553, 0.53231284, 0.31632463]])

In [26]:
np.random.randint(1,5, size=(3,4))

array([[2, 3, 4, 1],
       [1, 1, 4, 3],
       [1, 4, 3, 1]], dtype=int32)

In [27]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Practice

In [28]:
a = np.array([[1,2,3,4,5,6], [10,20,30,40,50,60], [12,12,12,12,12,12], [11,21,31,41,51,61], [13,24,34,44,54,64]])
a

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12, 12],
       [11, 21, 31, 41, 51, 61],
       [13, 24, 34, 44, 54, 64]])

In [29]:
a.shape

(5, 6)

In [30]:
a[:3, -5:]

array([[ 2,  3,  4,  5,  6],
       [20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12]])

In [31]:
a[0:3]

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12, 12]])

# Question 2